---
- name: Provision MongoDB Enterprise instance on Lightsail
  hosts: all
  gather_facts: true
  vars:
    mongo_instances:
      - a
      - b
      - c
  tasks:
    - name: Mongo key exist
      stat:
        path: "/etc/mongodb.key"
      register: mongo_key_exist

    - name: Generate MongoDB Key
      when: not mongo_key_exist.stat.exists
      ansible.builtin.shell: openssl rand -base64 741 > /etc/mongodb.key
      become: true

    - name: Create container data directory
      ansible.builtin.file:
        dest: /data/mongo-{{item}}/config
        owner: admin
        group: admin
        state: directory
        mode: 0755
      loop: "{{mongo_instances}}"
      become: true

    - name: Save MongoDB Key file.
      when: not mongo_key_exist.stat.exists
      ansible.builtin.copy:
        remote_src: true
        src: /etc/mongodb.key
        dest: /data/mongo-{{item}}/config/mongodb.key
        owner: 999
        group: admin
        mode: 0600
      become: true
      loop: "{{mongo_instances}}"

    - name: Copy Mongo config
      ansible.builtin.copy:
        src: config/mongod.conf
        dest: /data/mongo-{{item}}/config/mongod.conf
        owner: admin
        group: admin
        mode: 0644
      loop: "{{mongo_instances}}"

    - name: Ensure user data script have finished
      stat:
        path: "/root/{{key_id}}"
      register: finished
      until: finished.stat.exists
      retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutesdelay: 5 # Every 5 seconds
      become: true

    - name: Create Nomad data directory
      ansible.builtin.file:
        dest: /opt/nomad/
        owner: nomad
        group: nomad
        state: directory
        mode: 0755
      become: true

    - name: Copy Nomad configuration
      ansible.builtin.template:
        src: templates/nomad.hcl.j2
        dest: /etc/nomad.d/nomad.hcl
        owner: nomad
        group: nomad
        mode: 0644
      become: true

    - name: Create Nomad environment file
      ansible.builtin.copy:
        content: ""
        dest: /etc/nomad.d/nomad.env
        owner: nomad
        group: nomad
        mode: 0644
      become: true

    - name: Enable and start Nomad
      ansible.builtin.systemd:
        name: nomad
        state: started
        enabled: true
      become: true

    - name: Create job
      community.general.nomad_job:
        host: "{{ ansible_eth0.ipv4.address }}"
        state: present
        content: "{{ lookup('template', 'templates/mongodb.nomad.hcl.j2', variable_start_string='[[' , variable_end_string=']]' )}}"
        timeout: 300
        use_ssl: false

    - name: Get deployment
      ansible.builtin.uri:
        url: "http://{{ ansible_eth0.ipv4.address }}:4646/v1/job/mongo/deployments"
        return_content: yes
        validate_certs: no
        body_format: json
        status_code:
          - 200
      register: uri_output
      until: "{{ uri_output.json.0.TaskGroups.keys() | map('extract', uri_output.json.0.TaskGroups, ['HealthyAllocs']) | sum == uri_output.json.0.TaskGroups.keys() | length }}"
      retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutesdelay: 5 # Every 5 seconds
